version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "feat(ci)"
    labels:
      - "github-actions"
      - "dependencies"
    reviewers:
      - "Darkness4"


  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "feat(gradle)"
    labels:
      - "gradle"
      - "dependencies"
    reviewers:
      - "Darkness4"
